-- replaced with 7-arg version with defaults
DROP FUNCTION IF EXISTS invExpense(INTEGER, NUMERIC, INTEGER, TEXT, TEXT);
DROP FUNCTION IF EXISTS invExpense(INTEGER, NUMERIC, INTEGER, TEXT, TEXT, TIMESTAMP WITH TIME ZONE);

DROP FUNCTION IF EXISTS postInvTrans(INTEGER, TEXT, NUMERIC, TEXT, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS postInvTrans(INTEGER, TEXT, NUMERIC, TEXT, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER, INTEGER, TIMESTAMP WITH TIME ZONE);
DROP FUNCTION IF EXISTS postInvTrans(INTEGER, TEXT, NUMERIC, TEXT, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER, INTEGER, TIMESTAMP WITH TIME ZONE, NUMERIC);

DROP FUNCTION IF EXISTS postCCcashReceipt(INTEGER, INTEGER);
DROP FUNCTION IF EXISTS postCCcashReceipt(INTEGER, INTEGER, TEXT);

DROP FUNCTION IF EXISTS createarcreditmemo(INTEGER, INTEGER, TEXT, TEXT, DATE, NUMERIC, TEXT, INTEGER, INTEGER, INTEGER, DATE, INTEGER, INTEGER, NUMERIC, INTEGER);
DROP FUNCTION IF EXISTS createarcreditmemo(INTEGER, INTEGER, TEXT, TEXT, DATE, NUMERIC, TEXT, INTEGER, INTEGER, INTEGER, DATE, INTEGER, INTEGER, NUMERIC, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS createarcreditmemo(INTEGER, INTEGER, TEXT, TEXT, DATE, NUMERIC, TEXT, INTEGER, INTEGER, INTEGER, DATE, INTEGER, INTEGER, NUMERIC, INTEGER, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS createARCreditMemo(INTEGER, TEXT, TEXT, DATE, NUMERIC, TEXT);
DROP FUNCTION IF EXISTS createARCreditMemo(INTEGER, TEXT, TEXT, DATE, NUMERIC, TEXT, INTEGER);
DROP FUNCTION IF EXISTS createARCreditMemo(INTEGER, TEXT, TEXT, DATE, NUMERIC, TEXT, INTEGER, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS createarcreditmemo(INTEGER, TEXT, TEXT, DATE, NUMERIC, TEXT, INTEGER, INTEGER, INTEGER, DATE, INTEGER, INTEGER, NUMERIC);
DROP FUNCTION IF EXISTS createarcreditmemo(INTEGER, TEXT, TEXT, DATE, NUMERIC, TEXT, INTEGER, INTEGER, INTEGER, DATE, INTEGER, INTEGER, NUMERIC, INTEGER);
DROP FUNCTION IF EXISTS createarcreditmemo(INTEGER, TEXT, TEXT, DATE, NUMERIC, TEXT, INTEGER, INTEGER, INTEGER, DATE, INTEGER, INTEGER, NUMERIC, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS createarcreditmemo(INTEGER, TEXT, TEXT, DATE, NUMERIC, TEXT, INTEGER, INTEGER, INTEGER, DATE, INTEGER, INTEGER, NUMERIC, INTEGER, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS roundcost(NUMERIC);
DROP FUNCTION IF EXISTS roundsale(NUMERIC);

DROP FUNCTION IF EXISTS currconcat(VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS currconcat(INTEGER);
DROP FUNCTION IF EXISTS currgain(INTEGER, NUMERIC, DATE, DATE);
DROP FUNCTION IF EXISTS currtocurr(INTEGER, INTEGER, NUMERIC, DATE);
