BEGIN;

-- Drop columns in tax table

ALTER TABLE tax DROP COLUMN tax_ratea CASCADE;
ALTER TABLE tax DROP COLUMN tax_freight CASCADE;
ALTER TABLE tax DROP COLUMN tax_cumulative CASCADE;
ALTER TABLE tax DROP COLUMN tax_rateb CASCADE;
ALTER TABLE tax DROP COLUMN tax_salesb_accnt_id CASCADE;
ALTER TABLE tax DROP COLUMN tax_ratec CASCADE;
ALTER TABLE tax DROP COLUMN tax_salesc_accnt_id CASCADE;

-- Drop taxauth column in document tables

ALTER TABLE cmhead       DROP COLUMN cmhead_taxauth_id CASCADE;
ALTER TABLE cobmisc      DROP COLUMN cobmisc_taxauth_id CASCADE;
ALTER TABLE cohead       DROP COLUMN cohead_taxauth_id CASCADE;
ALTER TABLE custinfo     DROP COLUMN cust_taxauth_id CASCADE;
ALTER TABLE invchead     DROP COLUMN invchead_taxauth_id CASCADE;
ALTER TABLE itemtax      DROP COLUMN itemtax_taxauth_id CASCADE;
ALTER TABLE prospect     DROP COLUMN prospect_taxauth_id CASCADE;
ALTER TABLE quhead       DROP COLUMN quhead_taxauth_id CASCADE;
ALTER TABLE rahead       DROP COLUMN rahead_taxauth_id CASCADE;
ALTER TABLE shiptoinfo   DROP COLUMN shipto_taxauth_id CASCADE;
ALTER TABLE tohead       DROP COLUMN tohead_taxauth_id CASCADE;
ALTER TABLE vendaddrinfo DROP COLUMN vendaddr_taxauth_id CASCADE;
ALTER TABLE vendinfo     DROP COLUMN vend_taxauth_id CASCADE;
ALTER TABLE vohead       DROP COLUMN vohead_taxauth_id CASCADE;
ALTER TABLE whsinfo      DROP COLUMN warehous_taxauth_id CASCADE;

-- Drop tax columns in document tables that were NOT moved to taxhist

ALTER TABLE coitem        DROP COLUMN coitem_tax_id CASCADE;
ALTER TABLE quitem        DROP COLUMN quitem_tax_id CASCADE;
ALTER TABLE raitem        DROP COLUMN raitem_tax_id CASCADE;

ALTER TABLE custinfo      DROP COLUMN cust_tax_id CASCADE;
ALTER TABLE custinfo      DROP COLUMN cust_taxidnum CASCADE;
ALTER TABLE pohead        DROP COLUMN pohead_tax CASCADE;
ALTER TABLE quhead        DROP COLUMN quhead_tax_id CASCADE;
ALTER TABLE shiptoinfo    DROP COLUMN shipto_taxcode_id CASCADE;

-- Drop tax columns in document tables that were moved to taxhist

ALTER TABLE asohist       DROP COLUMN asohist_tax_id CASCADE;
ALTER TABLE asohist       DROP COLUMN asohist_tax_pcta CASCADE;
ALTER TABLE asohist       DROP COLUMN asohist_tax_pctb CASCADE;
ALTER TABLE asohist       DROP COLUMN asohist_tax_pctc CASCADE;
ALTER TABLE asohist       DROP COLUMN asohist_tax_ratea CASCADE;
ALTER TABLE asohist       DROP COLUMN asohist_tax_rateb CASCADE;
ALTER TABLE asohist       DROP COLUMN asohist_tax_ratec CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_tax_id CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_tax CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_tax_ratea CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_tax_rateb CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_tax_ratec CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_tax_curr_id CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_adjtax_id CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_adjtax_pcta CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_adjtax_pctb CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_adjtax_pctc CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_adjtax_ratea CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_adjtax_rateb CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_adjtax_ratec CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_freighttax_id CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_freighttax_pcta CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_freighttax_pctb CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_freighttax_pctc CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_freighttax_ratea CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_freighttax_rateb CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_freighttax_ratec CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_adjtaxtype_id CASCADE;
ALTER TABLE cmhead        DROP COLUMN cmhead_freighttax_id  CASCADE;
ALTER TABLE cmitem        DROP COLUMN cmitem_tax_id CASCADE;
ALTER TABLE cmitem        DROP COLUMN cmitem_tax_pcta CASCADE;
ALTER TABLE cmitem        DROP COLUMN cmitem_tax_pctb CASCADE;
ALTER TABLE cmitem        DROP COLUMN cmitem_tax_pctc CASCADE;
ALTER TABLE cmitem        DROP COLUMN cmitem_tax_ratea CASCADE;
ALTER TABLE cmitem        DROP COLUMN cmitem_tax_rateb CASCADE;
ALTER TABLE cmitem        DROP COLUMN cmitem_tax_ratec CASCADE;
ALTER TABLE cobill        DROP COLUMN cobill_tax_id CASCADE;
ALTER TABLE cobill        DROP COLUMN cobill_tax_pcta CASCADE;
ALTER TABLE cobill        DROP COLUMN cobill_tax_pctb CASCADE;
ALTER TABLE cobill        DROP COLUMN cobill_tax_pctc CASCADE;
ALTER TABLE cobill        DROP COLUMN cobill_tax_ratea CASCADE;
ALTER TABLE cobill        DROP COLUMN cobill_tax_rateb CASCADE;
ALTER TABLE cobill        DROP COLUMN cobill_tax_ratec CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_tax CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_adjtaxtype_id CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_freighttaxtype_id CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_tax_ratea CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_tax_rateb CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_tax_ratec CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_tax_curr_id CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_adjtax_id CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_adjtax_pcta CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_adjtax_pctb CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_adjtax_pctc CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_adjtax_ratea CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_adjtax_rateb CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_adjtax_ratec CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_freighttax_id CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_freighttax_pcta CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_freighttax_pctb CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_freighttax_pctc CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_freighttax_ratea CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_freighttax_rateb CASCADE;
ALTER TABLE cobmisc       DROP COLUMN cobmisc_freighttax_ratec CASCADE;
ALTER TABLE cohist        DROP COLUMN cohist_tax_id CASCADE;
ALTER TABLE cohist        DROP COLUMN cohist_tax_pcta CASCADE;
ALTER TABLE cohist        DROP COLUMN cohist_tax_pctb CASCADE;
ALTER TABLE cohist        DROP COLUMN cohist_tax_pctc CASCADE;
ALTER TABLE cohist        DROP COLUMN cohist_tax_ratea CASCADE;
ALTER TABLE cohist        DROP COLUMN cohist_tax_rateb CASCADE;
ALTER TABLE cohist        DROP COLUMN cohist_tax_ratec CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_tax CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_freighttaxtype_id CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_adjtaxtype_id CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_tax_ratea CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_tax_rateb CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_tax_ratec CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_tax_curr_id CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_adjtax_id CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_adjtax_pcta CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_adjtax_pctb CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_adjtax_pctc CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_adjtax_ratea CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_adjtax_rateb CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_adjtax_ratec CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_freighttax_id CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_freighttax_pcta CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_freighttax_pctb CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_freighttax_pctc CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_freighttax_ratea CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_freighttax_rateb CASCADE;
ALTER TABLE invchead      DROP COLUMN invchead_freighttax_ratec CASCADE;
ALTER TABLE invcitem      DROP COLUMN invcitem_tax_id CASCADE;
ALTER TABLE invcitem      DROP COLUMN invcitem_tax_pcta CASCADE;
ALTER TABLE invcitem      DROP COLUMN invcitem_tax_pctb CASCADE;
ALTER TABLE invcitem      DROP COLUMN invcitem_tax_pctc CASCADE;
ALTER TABLE invcitem      DROP COLUMN invcitem_tax_ratea CASCADE;
ALTER TABLE invcitem      DROP COLUMN invcitem_tax_rateb CASCADE;
ALTER TABLE invcitem      DROP COLUMN invcitem_tax_ratec CASCADE;
ALTER TABLE tax           DROP COLUMN tax_ratea;
ALTER TABLE tax           DROP COLUMN tax_freight;
ALTER TABLE tax           DROP COLUMN tax_cumulative;
ALTER TABLE tax           DROP COLUMN tax_rateb;
ALTER TABLE tax           DROP COLUMN tax_salesb_accnt_id;
ALTER TABLE tax           DROP COLUMN tax_ratec;
ALTER TABLE tax           DROP COLUMN tax_salesc_accnt_id;
ALTER TABLE tohead        DROP COLUMN tohead_freighttax_id CASCADE;
ALTER TABLE tohead        DROP COLUMN tohead_freighttax_pcta CASCADE;
ALTER TABLE tohead        DROP COLUMN tohead_freighttax_pctb CASCADE;
ALTER TABLE tohead        DROP COLUMN tohead_freighttax_pctc CASCADE;
ALTER TABLE tohead        DROP COLUMN tohead_freighttax_ratea CASCADE;
ALTER TABLE tohead        DROP COLUMN tohead_freighttax_rateb CASCADE;
ALTER TABLE tohead        DROP COLUMN tohead_freighttax_ratec CASCADE;
ALTER TABLE toitem        DROP COLUMN toitem_freighttax_id CASCADE;
ALTER TABLE toitem        DROP COLUMN toitem_freighttax_pcta CASCADE;
ALTER TABLE toitem        DROP COLUMN toitem_freighttax_pctb CASCADE;
ALTER TABLE toitem        DROP COLUMN toitem_freighttax_pctc CASCADE;
ALTER TABLE toitem        DROP COLUMN toitem_freighttax_ratea CASCADE;
ALTER TABLE toitem        DROP COLUMN toitem_freighttax_rateb CASCADE;
ALTER TABLE toitem        DROP COLUMN toitem_freighttax_ratec CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_tax_curr_id CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_adjtax_id CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_adjtax_pcta CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_adjtax_pctb CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_adjtax_pctc CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_adjtax_ratea CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_adjtax_rateb CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_adjtax_ratec CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_freighttax_id CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_freighttax_pcta CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_freighttax_pctb CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_freighttax_pctc CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_freighttax_ratea CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_freighttax_rateb CASCADE;
ALTER TABLE vohead        DROP COLUMN vohead_freighttax_ratec CASCADE;
ALTER TABLE voitem        DROP COLUMN voitem_tax_id CASCADE;
ALTER TABLE voitem        DROP COLUMN voitem_tax_pcta CASCADE;
ALTER TABLE voitem        DROP COLUMN voitem_tax_pctb CASCADE;
ALTER TABLE voitem        DROP COLUMN voitem_tax_pctc CASCADE;
ALTER TABLE voitem        DROP COLUMN voitem_tax_ratea CASCADE;
ALTER TABLE voitem        DROP COLUMN voitem_tax_rateb CASCADE;
ALTER TABLE voitem        DROP COLUMN voitem_tax_ratec CASCADE;
COMMIT;
