DELETE FROM report 
WHERE report_name IN (
'BookingsByCustomer',
'BookingsByCustomerGroup',
'BookingsByItem',
'BookingsByProductCategory',
'BookingsBySalesRep',
'BookingsByShipTo',
'TimePhasedBookingsByCustomer',
'TimePhasedBookingsByProductCategory',
'TimePhasedBookingsByItem',
'TimePhasedSalesHistoryByCustomer',
'TimePhasedSalesHistoryByItem',
'TimePhasedSalesHistoryByCustomerByItem',
'TimePhasedSalesHistoryByCustomerGroup',
'TimePhasedSalesHistoryByProductCategory',
'SalesHistoryByCustomerType',
'SalesHistoryByCustomerGroup',
'SalesHistoryByProductCategory',
'SalesHistoryByCustomer',
'SalesHistoryByParameterList',
'SalesHistoryByBilltoName',
'SalesHistoryByItem',
'SalesHistoryBySalesRep',
'SalesHistoryByShipTo',
'BriefSalesHistoryByCustomer',
'BriefSalesHistoryByCustomerType') 
AND report_grade=0;