CREATE OR REPLACE FUNCTION enterPoReceipt(INTEGER, NUMERIC) RETURNS INTEGER AS '
BEGIN
  RETURN enterReceipt(''PO'', $1, $2, 0.0, '''', NULL, NULL);
END;
' LANGUAGE 'plpgsql';


CREATE OR REPLACE FUNCTION enterPoReceipt(INTEGER, NUMERIC, TEXT) RETURNS INTEGER AS '
BEGIN
  RETURN enterPoReceipt(''PO'', $1, $2, 0.0, $3, NULL, NULL);
END;
' LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION enterPoReceipt(INTEGER, NUMERIC, NUMERIC, TEXT) RETURNS INTEGER AS '
BEGIN
  RETURN enterPoReceipt(''PO'', $1, $2, $3, $4, NULL, NULL);
END;
' LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION enterPoReceipt(INTEGER, NUMERIC, NUMERIC, TEXT, INTEGER, DATE) RETURNS INTEGER AS '
BEGIN
  RETURN enterReceipt(''PO'', $1, $2, $3, $4, $5, $6);
END;
' LANGUAGE 'plpgsql';
