function main()
{

    waitForObject(":_username_QLineEdit");
    type(":_username_QLineEdit", "admin");
    waitForObject(":_username_QLineEdit");
    type(":_username_QLineEdit", "<Tab>");
    waitForObject(":_password_QLineEdit");
    type(":_password_QLineEdit", "1zenqa1");
    waitForObject(":_password_QLineEdit");
    type(":_password_QLineEdit", "<Return>");
    
    waitForObjectItem(":xTuple ERP: OpenMFG Edition_QMenuBar", "Products");
    activateItem(":xTuple ERP: OpenMFG Edition_QMenuBar", "Products");
    waitForObjectItem(":xTuple ERP: OpenMFG Edition.Products_QMenu", "Item");
    activateItem(":xTuple ERP: OpenMFG Edition.Products_QMenu", "Item");
    waitForObjectItem(":xTuple ERP: OpenMFG Edition.Item_QMenu", "List...");
    activateItem(":xTuple ERP: OpenMFG Edition.Item_QMenu", "List...");
    waitForObject(":List Items.New_QPushButton");
    clickButton(":List Items.New_QPushButton");
    waitForObject(":_itemNumber_XLineEdit");
    type(":_itemNumber_XLineEdit", "YTRUCK1");
    if(!findObject(":Item.Active_QCheckBox").checked)
        clickButton(":Item.Active_QCheckBox");
    type(":_description1_XLineEdit", "Yellow Tough Truck");
    waitForObject(":_itemGroup_QComboBoxListView");
    type(":_itemGroup_QComboBoxListView", "<Return>");
    waitForObject(":_inventoryUOM_XComboBox");
    type(":_inventoryUOM_XComboBox", "EA");
    if(!findObject(":_itemGroup.Pick List_QCheckBox").checked)
        clickButton(":_itemGroup.Pick List_QCheckBox");
    
    waitForObject(":_itemGroup.Fractional_QCheckBox");
    clickButton(":_itemGroup.Fractional_QCheckBox");
    waitForObject(":_itemGroup.Fractional_QCheckBox");
    clickButton(":_itemGroup.Fractional_QCheckBox");
    waitForObject(":_itemGroup_XLineEdit");
    mouseClick(":_itemGroup_XLineEdit", 39, 11, 1, Qt.LeftButton);
    waitForObject(":_itemGroup_XLineEdit");
    type(":_itemGroup_XLineEdit", "5.00");
    waitForObject(":_itemGroup_QComboBoxListView");
    type(":_itemGroup_QComboBoxListView", "<Down>");
    waitForObject(":_itemGroup_QComboBoxListView");
    type(":_itemGroup_QComboBoxListView", "<Down>");
    waitForObject(":_itemGroup_QComboBoxListView");
    type(":_itemGroup_QComboBoxListView", "<Up>");
    waitForObject(":_itemGroup_QComboBoxListView");
    type(":_itemGroup_QComboBoxListView", "<Up>");
    waitForObject(":_itemGroup_QComboBoxListView");
    type(":_itemGroup_QComboBoxListView", "<Return>");
    waitForObject(":Item.widget_QWidget");
    mouseClick(":Item.widget_QWidget", 363, 189, 1, Qt.LeftButton);
    waitForObject(":_itemGroup._planningType_QComboBox");
    type(":_itemGroup._planningType_QComboBox", "<Alt>");
    waitForObject(":Item.Item is Sold_QGroupBox");
    mouseClick(":Item.Item is Sold_QGroupBox", 20, 11, 1, Qt.LeftButton);
    waitForObject(":Item.Item is Sold_QGroupBox");
    mouseClick(":Item.Item is Sold_QGroupBox", 20, 11, 1, Qt.LeftButton);
    waitForObject(":Item is Sold_QComboBoxListView");
    type(":Item is Sold_QComboBoxListView", "<Return>");
    waitForObject(":Item is Sold.Exclusive_QCheckBox");
    clickButton(":Item is Sold.Exclusive_QCheckBox");
    waitForObject(":Item is Sold.Exclusive_QCheckBox");
    clickButton(":Item is Sold.Exclusive_QCheckBox");
    waitForObject(":Item is Sold._listprice_XLineEdit");
    mouseClick(":Item is Sold._listprice_XLineEdit", 67, 9, 1, Qt.LeftButton);
    waitForObject(":Item is Sold._listprice_XLineEdit");
    type(":Item is Sold._listprice_XLineEdit", "10.99");
    waitForObject(":Item is Sold_QComboBoxListView");
    type(":Item is Sold_QComboBoxListView", "<Return>");
    waitForObject(":Item is Sold._priceUOM_XComboBox");
    type(":Item is Sold._priceUOM_XComboBox", "<Alt>");
    waitForObject(":Item is Sold.qt_spinbox_lineedit_QLineEdit");
    mouseDrag(":Item is Sold.qt_spinbox_lineedit_QLineEdit", 14, 7, -69, 0, 1, Qt.LeftButton);
    waitForObject(":Item is Sold._warranty_QSpinBox");
    type(":Item is Sold._warranty_QSpinBox", "<Ctrl+A>");
    waitForObject(":Item is Sold._warranty_QSpinBox");
    type(":Item is Sold._warranty_QSpinBox", "<Del>");
    waitForObject(":Item is Sold._warranty_QSpinBox");
    type(":Item is Sold._warranty_QSpinBox", "3");
    waitForObject(":Item is Sold._warranty_QSpinBox");
    type(":Item is Sold._warranty_QSpinBox", "6");
    waitForObject(":Item is Sold._warranty_QSpinBox");
    type(":Item is Sold._warranty_QSpinBox", "5");
    waitForObject(":Item is Sold._warranty_QSpinBox");
    type(":Item is Sold._warranty_QSpinBox", "<Tab>");
    waitForObject(":_prodWeight_XLineEdit");
    type(":_prodWeight_XLineEdit", "3.5");
    waitForObject(":_packWeight_XLineEdit");
    mouseClick(":_packWeight_XLineEdit", 37, 10, 1, Qt.LeftButton);
    waitForObject(":_packWeight_XLineEdit");
    type(":_packWeight_XLineEdit", ".25");
    waitForObject(":Item is Sold._upcCode_XLineEdit");
    mouseClick(":Item is Sold._upcCode_XLineEdit", 82, 8, 1, Qt.LeftButton);
    waitForObject(":Item is Sold._upcCode_XLineEdit");
    mouseClick(":Item is Sold._upcCode_XLineEdit", 25, 14, 1, Qt.LeftButton);
    waitForObject(":Item is Sold._upcCode_XLineEdit");
    type(":Item is Sold._upcCode_XLineEdit", "1234-");
    waitForObject(":Item is Sold._upcCode_XLineEdit");
    mouseClick(":Item is Sold._upcCode_XLineEdit", 57, 14, 1, Qt.LeftButton);
    waitForObject(":Item is Sold._upcCode_XLineEdit");
    type(":Item is Sold._upcCode_XLineEdit", "5432");
    waitForObject(":Item is Sold._upcCode_XLineEdit");
    mouseClick(":Item is Sold._upcCode_XLineEdit", 93, 11, 1, Qt.LeftButton);
    waitForObject(":Item.Save_QPushButton");
    clickButton(":Item.Save_QPushButton");
    waitForObject(":Item.No_QPushButton");
    clickButton(":Item.No_QPushButton");
    waitForObjectItem(":List Items._item_XTreeWidget", "TOY-TRUCKS");
    clickItem(":List Items._item_XTreeWidget", "TOY-TRUCKS", 55, 8, 1, Qt.LeftButton);
    waitForObject(":List Items._item_XTreeWidget");
    doubleClickItem(":List Items._item_XTreeWidget", "TOY-TRUCKS", 55, 8, 0, Qt.LeftButton);
    waitForObject(":Item.qt_tabwidget_tabbar_QTabBar");
    clickTab(":Item.qt_tabwidget_tabbar_QTabBar", "Characteristics");
    waitForObject(":xTuple ERP: OpenMFG Edition - [Item]_GUIClient");
    sendEvent("QMoveEvent", ":xTuple ERP: OpenMFG Edition - [Item]_GUIClient", 100, 102, 639, 111);
    waitForObject(":_characteristicsTab.New_QPushButton");
    clickButton(":_characteristicsTab.New_QPushButton");
    waitForObject(":Item_QComboBoxListView");
    type(":Item_QComboBoxListView", "<Down>");
    waitForObject(":Item_QComboBoxListView");
    type(":Item_QComboBoxListView", "<Return>");
    waitForObject(":_value_XLineEdit");
    mouseClick(":_value_XLineEdit", 152, 14, 1, Qt.LeftButton);
    waitForObject(":_value_XLineEdit");
    type(":_value_XLineEdit", "Yellow-PL126");
    waitForObject(":Item.Default_QCheckBox");
    clickButton(":Item.Default_QCheckBox");
    waitForObject(":Item.Save_QPushButton_2");
    clickButton(":Item.Save_QPushButton_2");
    waitForObject(":Item.qt_tabwidget_tabbar_QTabBar");
    clickTab(":Item.qt_tabwidget_tabbar_QTabBar", "Comments");
    waitForObject(":Item.Save_QPushButton");
    clickButton(":Item.Save_QPushButton");
    waitForObject(":List Items.Close_QPushButton");
    clickButton(":List Items.Close_QPushButton");

}
