#!/bin/bash

cd ../bin/loader.app/Contents/Frameworks
install_name_tool -id @executable_path/../Frameworks/libqt-mt.3.dylib libqt-mt.3.dylib

cd ../MacOS
install_name_tool -change libqt-mt.3.dylib @executable_path/../Frameworks/libqt-mt.3.dylib loader

