SELECT dropIfExists('VIEW', 'coship',	'public'),
       dropIfExists('VIEW', 'vendaddr',	'public'),
       dropIfExists('VIEW', 'vend',	'public'),
       dropIfExists('VIEW', 'porecv',	'public'),
       dropIfExists('VIEW', 'apchkitem','public'),
       dropIfExists('VIEW', 'cust',	'public'),
       dropIfExists('VIEW', 'sopack',	'public'),
       dropIfExists('VIEW', 'apchk',	'public'),
       dropIfExists('VIEW', 'cosmisc',	'public'),
       dropIfExists('VIEW', 'shipto',	'public');
