BEGIN;

SELECT dropIfExists('TABLE', 'lang');

CREATE TABLE lang (
  lang_id        SERIAL PRIMARY KEY,
  lang_qt_number INTEGER,
  lang_abbr3     TEXT,
  lang_abbr2     TEXT,
  lang_name      TEXT   NOT NULL
                  );
COMMENT ON TABLE lang IS
'Table mapping ISO 639-1 and 639-2 language codes to Qt''s enum QLocale::Language integer values. See http://www.loc.gov/standards/iso639-2/php/code_list.php and the QLocale documentation..';

COMMENT ON COLUMN lang.lang_abbr2 IS 'ISO 639-1 code for language';
COMMENT ON COLUMN lang.lang_abbr3 IS 'ISO 639-2 code for language. Where there is a choice between bibliographic (B) and terminology (T) usage, this value is the T code';
COMMENT ON COLUMN lang.lang_name  IS 'Name of a human language, taken from the ISO 639-2 documentation';

REVOKE ALL ON lang FROM PUBLIC;
GRANT ALL ON lang TO GROUP openmfg;

REVOKE ALL ON lang_lang_id_seq FROM PUBLIC;
GRANT ALL ON lang_lang_id_seq TO GROUP openmfg;

INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (1, 3, NULL, NULL, 'Afan');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (2, 156, NULL, NULL, 'Atsam');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (3, 16, NULL, NULL, 'Bhutani');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (4, 22, NULL, NULL, 'Byelorussian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (5, 23, NULL, NULL, 'Cambodian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (6, 158, NULL, NULL, 'Jju');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (7, 154, NULL, NULL, 'Koro');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (8, 68, NULL, NULL, 'Kurundi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (9, 69, NULL, NULL, 'Laothian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (10, 101, NULL, NULL, 'SerboCroatian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (11, 102, NULL, NULL, 'Sesotho');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (12, 103, NULL, NULL, 'Setswana');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (13, 107, NULL, NULL, 'Siswati');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (14, 164, NULL, NULL, 'Tyap');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (15, NULL, 'ace', NULL, 'Achinese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (16, NULL, 'ach', NULL, 'Acoli');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (17, NULL, 'ada', NULL, 'Adangme');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (18, NULL, 'ady', NULL, 'Adyghe; Adygei');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (19, NULL, 'afa', NULL, 'Afro-Asiatic.(Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (20, NULL, 'afh', NULL, 'Afrihili');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (21, NULL, 'ain', NULL, 'Ainu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (22, NULL, 'akk', NULL, 'Akkadian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (23, NULL, 'ale', NULL, 'Aleut');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (24, NULL, 'alg', NULL, 'Algonquian languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (25, NULL, 'alt', NULL, 'Southern Altai');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (26, NULL, 'ang', NULL, 'English, Old (ca.450-1100)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (27, NULL, 'anp', NULL, 'Angika');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (28, NULL, 'apa', NULL, 'Apache languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (29, NULL, 'arc', NULL, 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (30, NULL, 'arn', NULL, 'Mapudungun; Mapuche');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (31, NULL, 'arp', NULL, 'Arapaho');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (32, NULL, 'art', NULL, 'Artificial (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (33, NULL, 'arw', NULL, 'Arawak');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (34, NULL, 'ast', NULL, 'Asturian; Bable; Leonese; Asturleonese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (35, NULL, 'ath', NULL, 'Athapascan languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (36, NULL, 'aus', NULL, 'Australian languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (37, NULL, 'awa', NULL, 'Awadhi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (38, NULL, 'bad', NULL, 'Banda languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (39, NULL, 'bai', NULL, 'Bamileke languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (40, NULL, 'bal', NULL, 'Baluchi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (41, NULL, 'ban', NULL, 'Balinese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (42, NULL, 'bas', NULL, 'Basa');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (43, NULL, 'bat', NULL, 'Baltic (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (44, NULL, 'bej', NULL, 'Beja; Bedawiyet');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (45, NULL, 'bem', NULL, 'Bemba');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (46, NULL, 'ber', NULL, 'Berber (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (47, NULL, 'bho', NULL, 'Bhojpuri');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (48, NULL, 'bik', NULL, 'Bikol');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (49, NULL, 'bin', NULL, 'Bini; Edo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (50, NULL, 'bla', NULL, 'Siksika');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (51, NULL, 'bnt', NULL, 'Bantu (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (52, NULL, 'bra', NULL, 'Braj');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (53, NULL, 'btk', NULL, 'Batak languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (54, NULL, 'bua', NULL, 'Buriat');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (55, NULL, 'bug', NULL, 'Buginese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (56, 152, 'byn', NULL, 'Blin; Bilin');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (57, NULL, 'cad', NULL, 'Caddo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (58, NULL, 'cai', NULL, 'Central American Indian (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (59, NULL, 'car', NULL, 'Galibi Carib');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (60, NULL, 'cau', NULL, 'Caucasian (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (61, NULL, 'ceb', NULL, 'Cebuano');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (62, NULL, 'cel', NULL, 'Celtic (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (63, NULL, 'chb', NULL, 'Chibcha');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (64, NULL, 'chg', NULL, 'Chagatai');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (65, NULL, 'chk', NULL, 'Chuukese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (66, NULL, 'chm', NULL, 'Mari');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (67, NULL, 'chn', NULL, 'Chinook jargon');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (68, NULL, 'cho', NULL, 'Choctaw');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (69, NULL, 'chp', NULL, 'Chipewyan; Dene Suline');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (70, NULL, 'chr', NULL, 'Cherokee');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (71, NULL, 'chy', NULL, 'Cheyenne');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (72, NULL, 'cmc', NULL, 'Chamic languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (73, NULL, 'cop', NULL, 'Coptic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (74, NULL, 'cpe', NULL, 'Creoles and pidgins, English-based (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (75, NULL, 'cpf', NULL, 'Creoles and pidgins, French-based (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (76, NULL, 'cpp', NULL, 'Creoles and pidgins, Portuguese-based (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (77, NULL, 'crh', NULL, 'Crimean Tatar; Crimean Turkish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (78, NULL, 'crp', NULL, 'Creoles and pidgins (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (79, NULL, 'csb', NULL, 'Kashubian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (80, NULL, 'cus', NULL, 'Cushitic (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (81, NULL, 'dak', NULL, 'Dakota');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (82, NULL, 'dar', NULL, 'Dargwa');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (83, NULL, 'day', NULL, 'Land Dayak languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (84, NULL, 'del', NULL, 'Delaware');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (85, NULL, 'den', NULL, 'Slave (Athapascan)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (86, NULL, 'dgr', NULL, 'Dogrib');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (87, NULL, 'din', NULL, 'Dinka');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (88, NULL, 'doi', NULL, 'Dogri');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (89, NULL, 'dra', NULL, 'Dravidian (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (90, NULL, 'dsb', NULL, 'Lower Sorbian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (91, NULL, 'dua', NULL, 'Duala');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (92, NULL, 'dum', NULL, 'Dutch, Middle (ca.1050-1350)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (93, NULL, 'dyu', NULL, 'Dyula');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (94, NULL, 'efi', NULL, 'Efik');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (95, NULL, 'egy', NULL, 'Egyptian (Ancient)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (96, NULL, 'eka', NULL, 'Ekajuk');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (97, NULL, 'elx', NULL, 'Elamite');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (98, NULL, 'enm', NULL, 'English, Middle (1100-1500)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (99, NULL, 'ewo', NULL, 'Ewondo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (100, NULL, 'fan', NULL, 'Fang');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (101, NULL, 'fat', NULL, 'Fanti');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (102, NULL, 'fil', NULL, 'Filipino; Pilipino');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (103, NULL, 'fiu', NULL, 'Finno-Ugrian (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (104, NULL, 'fon', NULL, 'Fon');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (105, NULL, 'frm', NULL, 'French, Middle (ca.1400-1600)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (106, NULL, 'fro', NULL, 'French, Old (842-ca.1400)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (107, 38, 'frr', NULL, 'Northern Frisian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (108, 38, 'frs', NULL, 'Eastern Frisian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (109, 159, 'fur', NULL, 'Friulian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (110, 148, 'gaa', NULL, 'Ga');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (111, NULL, 'gay', NULL, 'Gayo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (112, NULL, 'gba', NULL, 'Gbaya');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (113, NULL, 'gem', NULL, 'Germanic (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (114, 153, 'gez', NULL, 'Geez');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (115, NULL, 'gil', NULL, 'Gilbertese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (116, NULL, 'gmh', NULL, 'German, Middle High (ca.1050-1500)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (117, NULL, 'goh', NULL, 'German, Old High (ca.750-1050)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (118, NULL, 'gon', NULL, 'Gondi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (119, NULL, 'gor', NULL, 'Gorontalo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (120, NULL, 'got', NULL, 'Gothic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (121, NULL, 'grb', NULL, 'Grebo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (122, NULL, 'grc', NULL, 'Greek, Ancient (to 1453)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (123, NULL, 'gsw', NULL, 'Swiss German; Alemannic; Alsatian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (124, NULL, 'gwi', NULL, 'Gwich''in');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (125, NULL, 'hai', NULL, 'Haida');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (126, 163, 'haw', NULL, 'Hawaiian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (127, NULL, 'hil', NULL, 'Hiligaynon');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (128, NULL, 'him', NULL, 'Himachali');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (129, NULL, 'hit', NULL, 'Hittite');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (130, NULL, 'hmn', NULL, 'Hmong');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (131, NULL, 'hsb', NULL, 'Upper Sorbian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (132, NULL, 'hup', NULL, 'Hupa hupa');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (133, NULL, 'iba', NULL, 'Iban');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (134, NULL, 'ijo', NULL, 'Ijo languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (135, NULL, 'ilo', NULL, 'Iloko');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (136, NULL, 'inc', NULL, 'Indic (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (137, NULL, 'ine', NULL, 'Indo-European (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (138, NULL, 'inh', NULL, 'Ingush');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (139, NULL, 'ira', NULL, 'Iranian (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (140, NULL, 'iro', NULL, 'Iroquoian languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (141, NULL, 'jbo', NULL, 'Lojban');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (142, NULL, 'jpr', NULL, 'Judeo-Persian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (143, NULL, 'jrb', NULL, 'Judeo-Arabic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (144, NULL, 'kaa', NULL, 'Kara-Kalpak');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (145, NULL, 'kab', NULL, 'Kabyle');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (146, NULL, 'kac', NULL, 'Kachin; Jingpho');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (147, 150, 'kam', NULL, 'Kamba');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (148, NULL, 'kar', NULL, 'Karen languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (149, NULL, 'kaw', NULL, 'Kawi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (150, NULL, 'kbd', NULL, 'Kabardian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (151, NULL, 'kha', NULL, 'Khasi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (152, NULL, 'khi', NULL, 'Khoisan (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (153, NULL, 'kho', NULL, 'Khotanese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (154, NULL, 'kmb', NULL, 'Kimbundu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (155, 147, 'kok', NULL, 'Konkani');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (156, NULL, 'kos', NULL, 'Kosraean');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (157, NULL, 'kpe', NULL, 'Kpelle');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (158, NULL, 'krc', NULL, 'Karachay-Balkar');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (159, NULL, 'krl', NULL, 'Karelian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (160, NULL, 'kro', NULL, 'Kru languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (161, NULL, 'kru', NULL, 'Kurukh');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (162, NULL, 'kum', NULL, 'Kumyk');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (163, NULL, 'kut', NULL, 'Kutenai');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (164, NULL, 'lad', NULL, 'Ladino');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (165, NULL, 'lah', NULL, 'Lahnda');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (166, NULL, 'lam', NULL, 'Lamba');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (167, NULL, 'lez', NULL, 'Lezghian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (168, NULL, 'lol', NULL, 'Mongo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (169, NULL, 'loz', NULL, 'Lozi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (170, NULL, 'lua', NULL, 'Luba-Lulua');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (171, NULL, 'lui', NULL, 'Luiseno');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (172, NULL, 'lun', NULL, 'Lunda');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (173, NULL, 'luo', NULL, 'Luo (Kenya and Tanzania)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (174, NULL, 'lus', NULL, 'Lushai');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (175, NULL, 'mad', NULL, 'Madurese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (176, NULL, 'mag', NULL, 'Magahi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (177, NULL, 'mai', NULL, 'Maithili');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (178, NULL, 'mak', NULL, 'Makasar');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (179, NULL, 'man', NULL, 'Mandingo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (180, NULL, 'map', NULL, 'Austronesian (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (181, NULL, 'mas', NULL, 'Masai');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (182, NULL, 'mdf', NULL, 'Moksha');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (183, NULL, 'mdr', NULL, 'Mandar');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (184, NULL, 'men', NULL, 'Mende');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (185, NULL, 'mga', NULL, 'Irish, Middle (900-1200)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (186, NULL, 'mic', NULL, 'Mi''kmaq; Micmac');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (187, NULL, 'min', NULL, 'Minangkabau');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (188, NULL, 'mis', NULL, 'Uncoded languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (189, NULL, 'mkh', NULL, 'Mon-Khmer (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (190, NULL, 'mnc', NULL, 'Manchu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (191, NULL, 'mni', NULL, 'Manipuri');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (192, NULL, 'mno', NULL, 'Manobo languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (193, NULL, 'moh', NULL, 'Mohawk');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (194, NULL, 'mos', NULL, 'Mossi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (195, NULL, 'mul', NULL, 'Multiple languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (196, NULL, 'mun', NULL, 'Munda languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (197, NULL, 'mus', NULL, 'Creek');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (198, NULL, 'mwl', NULL, 'Mirandese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (199, NULL, 'mwr', NULL, 'Marwari');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (200, NULL, 'myn', NULL, 'Mayan languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (201, NULL, 'myv', NULL, 'Erzya');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (202, NULL, 'nah', NULL, 'Nahuatl languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (203, NULL, 'nai', NULL, 'North American Indian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (204, NULL, 'nap', NULL, 'Neapolitan');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (205, NULL, 'nds', NULL, 'Low German; Low Saxon; German, Low; Saxon, Low');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (206, NULL, 'new', NULL, 'Nepal Bhasa; Newari');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (207, NULL, 'nia', NULL, 'Nias');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (208, NULL, 'nic', NULL, 'Niger-Kordofanian (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (209, NULL, 'niu', NULL, 'Niuean');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (210, NULL, 'nog', NULL, 'Nogai');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (211, NULL, 'non', NULL, 'Norse, Old');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (212, NULL, 'nqo', NULL, 'N''Ko');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (213, NULL, 'nso', NULL, 'Pedi; Sepedi; Northern Sotho');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (214, NULL, 'nub', NULL, 'Nubian languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (215, NULL, 'nwc', NULL, 'Classical Newari; Old Newari; Classical Nepal Bhasa');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (216, NULL, 'nym', NULL, 'Nyamwezi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (217, NULL, 'nyn', NULL, 'Nyankole');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (218, NULL, 'nyo', NULL, 'Nyoro');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (219, NULL, 'nzi', NULL, 'Nzima');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (220, NULL, 'osa', NULL, 'Osage');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (221, NULL, 'ota', NULL, 'Turkish, Ottoman (1500-1928)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (222, NULL, 'oto', NULL, 'Otomian languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (223, NULL, 'paa', NULL, 'Papuan (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (224, NULL, 'pag', NULL, 'Pangasinan');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (225, NULL, 'pal', NULL, 'Pahlavi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (226, NULL, 'pam', NULL, 'Pampanga; Kapampangan');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (227, NULL, 'pap', NULL, 'Papiamento');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (228, NULL, 'pau', NULL, 'Palauan');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (229, NULL, 'peo', NULL, 'Persian, Old (ca.600-400 B.C.)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (230, NULL, 'phi', NULL, 'Philippine (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (231, NULL, 'phn', NULL, 'Phoenician');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (232, NULL, 'pon', NULL, 'Pohnpeian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (233, NULL, 'pra', NULL, 'Prakrit languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (234, NULL, 'pro', NULL, 'Provencal, Old (to 1500)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (235, NULL, 'raj', NULL, 'Rajasthani');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (236, NULL, 'rap', NULL, 'Rapanui');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (237, NULL, 'rar', NULL, 'Rarotongan; Cook Islands Maori');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (238, NULL, 'roa', NULL, 'Romance (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (239, NULL, 'rom', NULL, 'Romany');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (240, NULL, 'rup', NULL, 'Aromanian; Arumanian; Macedo-Romanian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (241, NULL, 'sad', NULL, 'Sandawe');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (242, NULL, 'sah', NULL, 'Yakut');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (243, NULL, 'sai', NULL, 'South American Indian (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (244, NULL, 'sal', NULL, 'Salishan languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (245, NULL, 'sam', NULL, 'Samaritan Aramaic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (246, NULL, 'sas', NULL, 'Sasak');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (247, NULL, 'sat', NULL, 'Santali');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (248, NULL, 'scn', NULL, 'Sicilian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (249, NULL, 'sco', NULL, 'Scots');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (250, NULL, 'sel', NULL, 'Selkup');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (251, NULL, 'sem', NULL, 'Semitic (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (252, NULL, 'sga', NULL, 'Irish, Old (to 900)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (253, NULL, 'sgn', NULL, 'Sign languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (254, NULL, 'shn', NULL, 'Shan');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (255, 155, 'sid', NULL, 'Sidamo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (256, NULL, 'sio', NULL, 'Siouan languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (257, NULL, 'sit', NULL, 'Sino-Tibetan (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (258, NULL, 'sla', NULL, 'Slavic (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (259, NULL, 'sma', NULL, 'Southern Sami');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (260, NULL, 'smi', NULL, 'Sami languages (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (261, NULL, 'smj', NULL, 'Lule Sami');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (262, NULL, 'smn', NULL, 'Inari Sami');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (263, NULL, 'sms', NULL, 'Skolt Sami');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (264, NULL, 'snk', NULL, 'Soninke');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (265, NULL, 'sog', NULL, 'Sogdian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (266, NULL, 'son', NULL, 'Songhai languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (267, NULL, 'srn', NULL, 'Sranan Tongo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (268, NULL, 'srr', NULL, 'Serer');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (269, NULL, 'ssa', NULL, 'Nilo-Saharan (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (270, NULL, 'suk', NULL, 'Sukuma');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (271, NULL, 'sus', NULL, 'Susu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (272, NULL, 'sux', NULL, 'Sumerian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (273, NULL, 'syc', NULL, 'Classical Syriac');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (274, 151, 'syr', NULL, 'Syriac');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (275, NULL, 'tai', NULL, 'Tai (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (276, NULL, 'tem', NULL, 'Timne');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (277, NULL, 'ter', NULL, 'Tereno');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (278, NULL, 'tet', NULL, 'Tetum');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (279, 157, 'tig', NULL, 'Tigre');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (280, NULL, 'tiv', NULL, 'Tiv');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (281, NULL, 'tkl', NULL, 'Tokelau');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (282, NULL, 'tlh', NULL, 'Klingon');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (283, NULL, 'tli', NULL, 'Tlingit');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (284, NULL, 'tmh', NULL, 'Tamashek');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (285, NULL, 'tog', NULL, 'Tonga (Nyasa)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (286, NULL, 'tpi', NULL, 'Tok Pisin');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (287, NULL, 'tsi', NULL, 'Tsimshian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (288, NULL, 'tum', NULL, 'Tumbuka');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (289, NULL, 'tup', NULL, 'Tupi languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (290, NULL, 'tut', NULL, 'Altaic (Other)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (291, NULL, 'tvl', NULL, 'Tuvalu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (292, NULL, 'tyv', NULL, 'Tuvinian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (293, NULL, 'udm', NULL, 'Udmurt');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (294, NULL, 'uga', NULL, 'Ugaritic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (295, NULL, 'umb', NULL, 'Umbundu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (296, NULL, 'und', NULL, 'Undetermined');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (297, NULL, 'vai', NULL, 'Vai');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (298, NULL, 'vot', NULL, 'Votic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (299, NULL, 'wak', NULL, 'Wakashan languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (300, 162, 'wal', NULL, 'Walamo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (301, NULL, 'war', NULL, 'Waray');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (302, NULL, 'was', NULL, 'Washo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (303, NULL, 'wen', NULL, 'Sorbian languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (304, NULL, 'xal', NULL, 'Kalmyk; Oirat');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (305, NULL, 'yao', NULL, 'Yao');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (306, NULL, 'yap', NULL, 'Yapese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (307, NULL, 'ypk', NULL, 'Yupik languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (308, NULL, 'zap', NULL, 'Zapotec');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (309, NULL, 'zbl', NULL, 'Blissymbols; Blissymbolics; Bliss');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (310, NULL, 'zen', NULL, 'Zenaga');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (311, NULL, 'znd', NULL, 'Zande languages');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (312, NULL, 'zun', NULL, 'Zuni');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (313, NULL, 'zxx', NULL, 'No linguistic content');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (314, NULL, 'zza', NULL, 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (315, 4, 'aar', 'aa', 'Afar');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (316, 2, 'abk', 'ab', 'Abkhazian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (317, NULL, 'ave', 'ae', 'Avestan');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (318, 5, 'afr', 'af', 'Afrikaans');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (319, 146, 'aka', 'ak', 'Akan');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (320, 7, 'amh', 'am', 'Amharic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (321, NULL, 'arg', 'an', 'Aragonese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (322, 8, 'ara', 'ar', 'Arabic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (323, 10, 'asm', 'as', 'Assamese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (324, NULL, 'ava', 'av', 'Avaric');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (325, 11, 'aym', 'ay', 'Aymara');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (326, 12, 'aze', 'az', 'Azerbaijani');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (327, 13, 'bak', 'ba', 'Bashkir');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (328, NULL, 'bel', 'be', 'Belarusian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (329, 20, 'bul', 'bg', 'Bulgarian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (330, 17, 'bih', 'bh', 'Bihari');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (331, 18, 'bis', 'bi', 'Bislama');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (332, NULL, 'bam', 'bm', 'Bambara');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (333, 15, 'ben', 'bn', 'Bengali');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (334, 121, 'bod', 'bo', 'Tibetan');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (335, 19, 'bre', 'br', 'Breton');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (336, 142, 'bos', 'bs', 'Bosnian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (337, 24, 'cat', 'ca', 'Catalan; Valencian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (338, NULL, 'che', 'ce', 'Chechen');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (339, NULL, 'cha', 'ch', 'Chamorro');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (340, 26, 'cos', 'co', 'Corsican');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (341, NULL, 'cre', 'cr', 'Cree');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (342, 28, 'ces', 'cs', 'Czech');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (343, NULL, 'chu', 'cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (344, NULL, 'chv', 'cv', 'Chuvash');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (345, 134, 'cym', 'cy', 'Welsh');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (346, 29, 'dan', 'da', 'Danish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (347, 42, 'deu', 'de', 'German');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (348, 143, 'div', 'dv', 'Divehi; Dhivehi; Maldivian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (349, NULL, 'dzo', 'dz', 'Dzongkha');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (350, 161, 'ewe', 'ee', 'Ewe');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (351, 42, 'ell', 'el', 'Greek, Modern (1453-)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (352, 31, 'eng', 'en', 'English');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (353, 32, 'epo', 'eo', 'Esperanto');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (354, 111, 'spa', 'es', 'Spanish; Castilian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (355, 33, 'est', 'et', 'Estonian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (356, 14, 'eus', 'eu', 'Basque');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (357, 89, 'fas', 'fa', 'Persian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (358, NULL, 'ful', 'ff', 'Fulah');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (359, 36, 'fin', 'fi', 'Finnish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (360, 35, 'fij', 'fj', 'Fijian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (361, 34, 'fao', 'fo', 'Faroese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (362, 37, 'fra', 'fr', 'French');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (363, 38, 'fry', 'fy', 'Western Frisian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (364, 57, 'gle', 'ga', 'Irish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (365, 39, 'gla', 'gd', 'Gaelic; Scottish Gaelic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (366, 40, 'glg', 'gl', 'Galician');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (367, 45, 'grn', 'gn', 'Guarani');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (368, 46, 'guj', 'gu', 'Gujarati');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (369, 144, 'glv', 'gv', 'Manx');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (370, 47, 'hau', 'ha', 'Hausa');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (371, 48, 'heb', 'he', 'Hebrew');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (372, 49, 'hin', 'hi', 'Hindi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (373, NULL, 'hmo', 'ho', 'Hiri Motu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (374, 27, 'hrv', 'hr', 'Croatian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (375, NULL, 'hat', 'ht', 'Haitian; Haitian Creole');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (376, 50, 'hun', 'hu', 'Hungarian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (377, 9, 'hye', 'hy', 'Armenian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (378, NULL, 'her', 'hz', 'Herero');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (379, 53, 'ina', 'ia', 'Interlingua (International Auxiliary language Association)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (380, 52, 'ind', 'id', 'Indonesian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (381, 54, 'ile', 'ie', 'Interlingue; Occidental');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (382, 149, 'ibo', 'ig', 'Igbo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (383, NULL, 'iii', 'ii', 'Sichuan Yi; Nuosu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (384, 56, 'ipk', 'ik', 'Inupiaq');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (385, NULL, 'ido', 'io', 'Ido');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (386, 51, 'isl', 'is', 'Icelandic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (387, 58, 'ita', 'it', 'Italian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (388, 55, 'iku', 'iu', 'Inuktitut');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (389, 59, 'jpn', 'ja', 'Japanese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (390, 60, 'jav', 'jv', 'Javanese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (391, 41, 'kat', 'ka', 'Georgian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (392, NULL, 'kon', 'kg', 'Kongo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (393, NULL, 'kik', 'ki', 'Kikuyu; Gikuyu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (394, NULL, 'kua', 'kj', 'Kuanyama; Kwanyama');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (395, 63, 'kaz', 'kk', 'Kazakh');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (396, 44, 'kal', 'kl', 'Kalaallisut; Greenlandic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (397, NULL, 'khm', 'km', 'Central Khmer');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (398, 61, 'kan', 'kn', 'Kannada');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (399, 66, 'kor', 'ko', 'Korean');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (400, NULL, 'kau', 'kr', 'Kanuri');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (401, 62, 'kas', 'ks', 'Kashmiri');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (402, 67, 'kur', 'ku', 'Kurdish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (403, NULL, 'kom', 'kv', 'Komi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (404, 145, 'cor', 'kw', 'Cornish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (405, 65, 'kir', 'ky', 'Kirghiz; Kyrgyz');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (406, 70, 'lat', 'la', 'Latin');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (407, NULL, 'ltz', 'lb', 'Luxembourgish; Letzeburgesch');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (408, NULL, 'lug', 'lg', 'Ganda');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (409, NULL, 'lim', 'li', 'Limburgan; Limburger; Limburgish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (410, 72, 'lin', 'ln', 'Lingala');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (411, NULL, 'lao', 'lo', 'Lao');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (412, 73, 'lit', 'lt', 'Lithuanian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (413, NULL, 'lub', 'lu', 'Luba-Katanga');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (414, 71, 'lav', 'lv', 'Latvian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (415, 75, 'mlg', 'mg', 'Malagasy');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (416, NULL, 'mah', 'mh', 'Marshallese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (417, 79, 'mri', 'mi', 'Maori');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (418, 74, 'mkd', 'mk', 'Macedonian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (419, 77, 'mal', 'ml', 'Malayalam');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (420, 82, 'mon', 'mn', 'Mongolian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (421, 81, 'mol', 'mo', 'Moldavian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (422, 80, 'mar', 'mr', 'Marathi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (423, 76, 'msa', 'ms', 'Malay');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (424, 78, 'mlt', 'mt', 'Maltese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (425, 21, 'mya', 'my', 'Burmese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (426, 83, 'nau', 'na', 'Nauru');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (427, 85, 'nob', 'nb', 'Bokmal, Norwegian; Norwegian Bokmal');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (428, NULL, 'nde', 'nd', 'Ndebele, North; North Ndebele');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (429, 84, 'nep', 'ne', 'Nepali');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (430, NULL, 'ndo', 'ng', 'Ndonga');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (431, 30, 'nld', 'nl', 'Dutch; Flemish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (432, 141, 'nno', 'nn', 'Norwegian Nynorsk; Nynorsk, Norwegian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (433, 141, 'nor', 'no', 'Norwegian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (434, NULL, 'nbl', 'nr', 'Ndebele, South; South Ndebele');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (435, NULL, 'nav', 'nv', 'Navajo; Navaho');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (436, 165, 'nya', 'ny', 'Chichewa; Chewa; Nyanja');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (437, 86, 'oci', 'oc', 'Occitan (post 1500); Provencal');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (438, NULL, 'oji', 'oj', 'Ojibwa');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (439, NULL, 'orm', 'om', 'Oromo');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (440, 87, 'ori', 'or', 'Oriya');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (441, NULL, 'oss', 'os', 'Ossetian; Ossetic');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (442, 92, 'pan', 'pa', 'Panjabi; Punjabi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (443, NULL, 'pli', 'pi', 'Pali');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (444, 90, 'pol', 'pl', 'Polish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (445, 88, 'pus', 'ps', 'Pushto; Pashto');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (446, 91, 'por', 'pt', 'Portuguese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (447, 93, 'que', 'qu', 'Quechua');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (448, 94, 'roh', 'rm', 'Romansh');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (449, NULL, 'run', 'rn', 'Rundi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (450, 95, 'ron', 'ro', 'Romanian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (451, 96, 'rus', 'ru', 'Russian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (452, 64, 'kin', 'rw', 'Kinyarwanda');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (453, 99, 'san', 'sa', 'Sanskrit');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (454, NULL, 'srd', 'sc', 'Sardinian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (455, 105, 'snd', 'sd', 'Sindhi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (456, NULL, 'sme', 'se', 'Northern Sami');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (457, 98, 'sag', 'sg', 'Sango');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (458, 106, 'sin', 'si', 'Sinhala; Sinhalese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (459, 108, 'slk', 'sk', 'Slovak');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (460, 109, 'slv', 'sl', 'Slovenian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (461, 97, 'smo', 'sm', 'Samoan');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (462, 104, 'sna', 'sn', 'Shona');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (463, 110, 'som', 'so', 'Somali');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (464, 6, 'sqi', 'sq', 'Albanian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (465, 100, 'srp', 'sr', 'Serbian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (466, NULL, 'ssw', 'ss', 'Swati');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (467, NULL, 'sot', 'st', 'Sotho, Southern');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (468, 112, 'sun', 'su', 'Sundanese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (469, 114, 'swe', 'sv', 'Swedish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (470, 113, 'swa', 'sw', 'Swahili');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (471, 117, 'tam', 'ta', 'Tamil');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (472, 119, 'tel', 'te', 'Telugu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (473, 116, 'tgk', 'tg', 'Tajik');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (474, 120, 'tha', 'th', 'Thai');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (475, 122, 'tir', 'ti', 'Tigrinya');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (476, 126, 'tuk', 'tk', 'Turkmen');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (477, 115, 'tgl', 'tl', 'Tagalog');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (478, NULL, 'tsn', 'tn', 'Tswana');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (479, 123, 'ton', 'to', 'Tonga (Tonga Islands)');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (480, 125, 'tur', 'tr', 'Turkish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (481, 124, 'tso', 'ts', 'Tsonga');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (482, 118, 'tat', 'tt', 'Tatar');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (483, 127, 'twi', 'tw', 'Twi');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (484, NULL, 'tah', 'ty', 'Tahitian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (485, 128, 'uig', 'ug', 'Uighur; Uyghur');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (486, 129, 'ukr', 'uk', 'Ukrainian');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (487, 130, 'urd', 'ur', 'Urdu');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (488, 131, 'uzb', 'uz', 'Uzbek');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (489, 160, 'ven', 've', 'Venda');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (490, 132, 'vie', 'vi', 'Vietnamese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (491, 133, 'vol', 'vo', 'Volapak');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (492, NULL, 'wln', 'wa', 'Walloon');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (493, 135, 'wol', 'wo', 'Wolof');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (494, 136, 'xho', 'xh', 'Xhosa');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (495, 137, 'yid', 'yi', 'Yiddish');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (496, 138, 'yor', 'yo', 'Yoruba');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (497, 139, 'zha', 'za', 'Zhuang; Chuang');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (498, 25, 'zho', 'zh', 'Chinese');
INSERT INTO lang (lang_id, lang_qt_number, lang_abbr3, lang_abbr2, lang_name) VALUES (499, 140, 'zul', 'zu', 'Zulu');

SELECT pg_catalog.setval('lang_lang_id_seq', 499, true);

COMMIT;
