ALTER TABLE pohead ADD COLUMN pohead_vend_cntct_id integer REFERENCES cntct (cntct_id);
ALTER TABLE pohead ADD COLUMN pohead_vend_cntct_honorific text;
ALTER TABLE pohead ADD COLUMN pohead_vend_cntct_first_name text;
ALTER TABLE pohead ADD COLUMN pohead_vend_cntct_middle text;
ALTER TABLE pohead ADD COLUMN pohead_vend_cntct_last_name text;
ALTER TABLE pohead ADD COLUMN pohead_vend_cntct_suffix text;
ALTER TABLE pohead ADD COLUMN pohead_vend_cntct_phone text;
ALTER TABLE pohead ADD COLUMN pohead_vend_cntct_title text;
ALTER TABLE pohead ADD COLUMN pohead_vend_cntct_fax text;
ALTER TABLE pohead ADD COLUMN pohead_vend_cntct_email text;
ALTER TABLE pohead ADD COLUMN pohead_vendaddress1 text;
ALTER TABLE pohead ADD COLUMN pohead_vendaddress2 text;
ALTER TABLE pohead ADD COLUMN pohead_vendaddress3 text;
ALTER TABLE pohead ADD COLUMN pohead_vendcity text;
ALTER TABLE pohead ADD COLUMN pohead_vendstate text;
ALTER TABLE pohead ADD COLUMN pohead_vendzipcode text;
ALTER TABLE pohead ADD COLUMN pohead_vendcountry text;
ALTER TABLE pohead ADD COLUMN pohead_shipto_cntct_id integer REFERENCES cntct (cntct_id);
ALTER TABLE pohead ADD COLUMN pohead_shipto_cntct_honorific text;
ALTER TABLE pohead ADD COLUMN pohead_shipto_cntct_first_name text;
ALTER TABLE pohead ADD COLUMN pohead_shipto_cntct_middle text;
ALTER TABLE pohead ADD COLUMN pohead_shipto_cntct_last_name text;
ALTER TABLE pohead ADD COLUMN pohead_shipto_cntct_suffix text;
ALTER TABLE pohead ADD COLUMN pohead_shipto_cntct_phone text;
ALTER TABLE pohead ADD COLUMN pohead_shipto_cntct_title text;
ALTER TABLE pohead ADD COLUMN pohead_shipto_cntct_fax text;
ALTER TABLE pohead ADD COLUMN pohead_shipto_cntct_email text;
ALTER TABLE pohead ADD COLUMN pohead_shiptoddress_id int REFERENCES addr (addr_id);
ALTER TABLE pohead ADD COLUMN pohead_shiptoaddress1 text;
ALTER TABLE pohead ADD COLUMN pohead_shiptoaddress2 text;
ALTER TABLE pohead ADD COLUMN pohead_shiptoaddress3 text;
ALTER TABLE pohead ADD COLUMN pohead_shiptocity text;
ALTER TABLE pohead ADD COLUMN pohead_shiptostate text;
ALTER TABLE pohead ADD COLUMN pohead_shiptozipcode text;
ALTER TABLE pohead ADD COLUMN pohead_shiptocountry text;
ALTER TABLE pohead ADD COLUMN pohead_cohead_id integer REFERENCES cohead (cohead_id) ON DELETE SET NULL;
