CREATE OR REPLACE FUNCTION deleteUOM(INTEGER) RETURNS INTEGER AS '
DECLARE
  pUomconvid ALIAS FOR $1;

BEGIN
  DELETE FROM uomconv WHERE uomconv_id=pUomconvid;

  RETURN 0;
END;
' LANGUAGE 'plpgsql';
