######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 7 15:02:22 2011
######################################################################

TEMPLATE = app
TARGET = classcode_cli
DEPENDPATH += .
INCLUDEPATH += . ../../../src

LIBS += -L../../../lib -lxtlib

CONFIG += qt warn_on console
QT += sql

OBJECTS_DIR=tmp
MOC_DIR=tmp
UI_DIR=tmp

# Input
SOURCES += main.cpp

